# Generated by Django 6.0 on 2026-01-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='signup',
        ),
    ]
